apiVersion: compliance.openshift.io/v1alpha1
kind: ScanSettingBinding
metadata:
  name: lab-cis-tailored-binding
  namespace: openshift-compliance
profiles:
  - apiGroup: compliance.openshift.io/v1alpha1
    kind: TailoredProfile
    name: lab-cis-tailored
settingsRef:
  apiGroup: compliance.openshift.io/v1alpha1
  kind: ScanSetting
  name: lab-weekly-scan-setting
