apiVersion: olm.operatorframework.io/v1
kind: ClusterExtension
metadata:
  name: rhacs-operator-v1
spec:
  namespace: rhacs-operator-v1-demo
  serviceAccount:
    name: rhacs-operator-v1-installer
  source:
    sourceType: Catalog
    catalog:
      packageName: rhacs-operator
      channels: ["stable"]
      upgradeConstraintPolicy: CatalogProvided
