apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: lab-sigstore-policy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: registry.access.redhat.com/ubi9/ubi-micro:latest
          command: ["sleep", "infinity"]
