apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-kv-store
  namespace: app
spec:
  provider:
    azurekv:
      authType: ServicePrincipal
      vaultUrl: "https://<KEYVAULT_NAME>.vault.azure.net"
      tenantId: "<AZURE_TENANT_ID>"
      authSecretRef:
        clientId:
          name: azure-spn
          key: ClientID
        clientSecret:
          name: azure-spn
          key: ClientSecret
