apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-local-secret-to-akv
  namespace: app
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: azure-kv-store
      kind: SecretStore
  selector:
    secret:
      name: source-secret
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: minha-secret-na-keyvault
