apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-store
  namespace: eso-demo
spec:
  provider:
    azurekv:
      authType: ServicePrincipal
      environmentType: PublicCloud
      vaultUrl: "https://<KEYVAULT_NAME>.vault.azure.net"
      tenantId: "<AZURE_TENANT_ID>"
      authSecretRef:
        clientId:
          name: azure-kv-sp
          key: ClientID
        clientSecret:
          name: azure-kv-sp
          key: ClientSecret
