apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-app-es
  namespace: eso-demo
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: azure-store
    kind: SecretStore
  target:
    name: demo-app-secret
    creationPolicy: Owner
  data:
    - secretKey: APP_PASSWORD
      remoteRef:
        key: demo-password
