apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-azure
  namespace: policies-acm
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: placement-azure
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: policy-oauth-configuration
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: policy-cluster-admin-rbac
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: policy-worker-3-per-zone
