apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pdb-demo
  namespace: lab-upgrade-status
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-pdb-demo
  template:
    metadata:
      labels:
        app: nginx-pdb-demo
    spec:
      containers:
        - name: nginx
          image: quay.io/packit/nginx-unprivileged:latest
          ports:
            - containerPort: 8080
